### ISSUE TITLE
[TC-ACE-2.1/2.2] test failed on python script

### ISSUE THREAD

**Issue by liangpy4** [project-chip/matter-test-scripts#153]
## Summary Title: 
test failed on python script

## Description:
the log shows error:
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.316 INFO ###########################################################
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.316 INFO Start of actual tests
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.317 INFO ###########################################################
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.317 INFO >>> [E:17213i S:42740 M:154721826 (Ack:189623101)] (S) Msg RX from 1:0000000012344321 [4975] --- Type 0000:10 (SecureChannel:StandaloneAck)
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.320 ERROR Error in AccessChecker#setup_class.
[2024-02-05 13:51:25] Traceback (most recent call last):
[2024-02-05 13:51:25]   File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 418, in _setup_class
[2024-02-05 13:51:25]     self.setup_class()
[2024-02-05 13:51:25]   File "/root/python_testing/matter_testing_support.py", line 1386, in async_runner
[2024-02-05 13:51:25]     return asyncio.run(runner_with_timeout)
[2024-02-05 13:51:25]   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-02-05 13:51:25]     return loop.run_until_complete(main)
[2024-02-05 13:51:25]   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[2024-02-05 13:51:25]     return future.result()
[2024-02-05 13:51:25]   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
[2024-02-05 13:51:25]     return fut.result()
[2024-02-05 13:51:25]   File "/root/python_testing/TC_AccessChecker.py", line 56, in setup_class
[2024-02-05 13:51:25]     self.xml_clusters, self.problems = build_xml_clusters()
[2024-02-05 13:51:25]   File "/root/python_testing/spec_parsing_support.py", line 461, in build_xml_clusters
[2024-02-05 13:51:25]     mask = clusters[descriptor_id].feature_map[code]
[2024-02-05 13:51:25] KeyError: 29
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.326 INFO            ***** Test Failure : 
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.327 INFO Finished test in 4162ms
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.341 INFO Summary for test class AccessChecker: Error 1, Executed 0, Failed 0, Passed 0, Requested 1, Skipped 1
[2024-02-05 13:51:25] [MatterTest] 02-05 05:51:25.343 INFO Summary for test run MatterTest@02-05-2024_05-51-03-204:
[2024-02-05 13:51:25] Total time elapsed 22.13613770700067s

## Steps to reproduce:
1. Launch docker in the raspberrypi.
2. run python scripts(please choose pairing method according to your device):
python3 TC_AccessChecker.py  --commissioning-method on-network --discriminator 3840 --passcode 20202021  --storage-path admin_storage.json --paa-trust-store-path /credentials/development/paa-root-certs/  --tests test_TC_ACE_2_1
python3 TC_AccessChecker.py  --commissioning-method on-network --discriminator 3840 --passcode 20202021  --storage-path admin_storage.json --paa-trust-store-path /credentials/development/paa-root-certs/  --tests test_TC_ACE_2_2

## Logs:
[[TC-ACE-2.2]_[zNw7rlE3]_CHIPTool_log.log](https://github.com/project-chip/matter-test-scripts/files/14179593/TC-ACE-2.2._.zNw7rlE3._CHIPTool_log.log)
[[TC-ACE-2.1]_[zNw7rlE3]_CHIPTool_log.log](https://github.com/project-chip/matter-test-scripts/files/14179594/TC-ACE-2.1._.zNw7rlE3._CHIPTool_log.log)

**Comment by cecille** [comment]
This is a test timeout. Please use the timeout config parameter to adjust according to your device size and network conditions. https://github.com/project-chip/matter-test-scripts/pull/136/files#diff-f9d18ed200f5ed9f3b8bbf15b53668784cf69e257ac11454cde939d7fc66b8dc

**Comment by liangpy4** [comment]
These 2 cases were passed at the SVE.
