### ISSUE TITLE
[TC-SWTCH-2.5][TC-SWTCH-2.6] `mobly.signals.TestFailure: Details=The --app-pid flag` failure always

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/matter-test-scripts#337]
## Summary Title: 

TC-SWTCH-2.5 and -2.6 suffer from a failure due to CI test code that has a bug.

## Description:

There is a path in those tests where a missing `()` on a method call (`if self._use_button_simulator` --> always true versus `if self._use_button_simulator()` correct) causes a failure when run against real devices.

## Steps to reproduce:
Run these scripts to completion with MSM feature.

## Logs:

```
[MatterTest] 08-14 10:53:43.039 ERROR Exception occurred in test_TC_SWTCH_2_6.
Traceback (most recent call last):
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/pyenv/lib/python3.11/site-packages/mobly/base_test.py", line 818, in exec_one_test
    test_method()
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/src/python_testing/matter_testing_support.py", line 1924, in per_endpoint_runner
    _async_runner(body, self, *args, **kwargs)
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/src/python_testing/matter_testing_support.py", line 1732, in _async_runner
    return asyncio.run(runner_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/src/python_testing/TC_SWTCH.py", line 845, in test_TC_SWTCH_2_6
    self._send_multi_press_named_pipe_command(endpoint_id, number_of_presses=1,
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/src/python_testing/TC_SWTCH.py", line 93, in _send_multi_press_named_pipe_command
    self._send_named_pipe_command(command_dict)
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/src/python_testing/TC_SWTCH.py", line 74, in _send_named_pipe_command
    asserts.fail("The --app-pid flag must be set when usage of button simulation named pipe is required (e.g. CI)")
  File "/usr/local/google/home/tennessee/repos/connectedhomeip/pyenv/lib/python3.11/site-packages/mobly/asserts.py", line 441, in fail
    raise signals.TestFailure(msg, extras)
mobly.signals.TestFailure: Details=The --app-pid flag must be set when usage of button simulation named pipe is required (e.g. CI), Extras=None
[MatterTest] 08-14 10:53:43.048 INFO 		***** Test Failure : 
```

**Comment by cecille** [comment]
https://github.com/project-chip/connectedhomeip/pull/34986 is the fix here
